
server:
  port: 18080
hapi:
  fhir:
    version: r4
    server:
      path: /fhir/*
    rest:
      server-name: hapi-fhir-ignite-server-ws
      server-version: 1.0.0
      implementation-description: Spring Boot Ingite Backend Server Sample
      default-response-encoding: json
      e-tag-support: enabled
      default-pretty-print: true
    validation:
      enabled: true
      request-only: true


management:
  security:
    enabled: false
logging:
  level:
    ca.uhn.fhir.jaxrs: debug
    
    
    
    
    
ignite:
  connect:
    address: 127.0.0.1
    
  mode: server